(define (problem p1)
 (:domain adder)
 (:objects t f tmp1 tmp2 x1 y1 r1 z1 r2 z2 - bit)
 (:init (and
	 (high t) (low f)
	 (low r1) (low r2) 
	 (low z1) (low z2) 
	 (unknown (low x1))
	 (unknown (high x1))
	 (oneof (low x1) (high x1))
	 (unknown (low y1))
	 (unknown (high y1))
	 (oneof (low y1) (high y1))
	 (constant x1) 
	 (constant y1)
	 )
  )
 (:goal (and (low r1)
	 (or (low z2) (high r2))
	 (or (low r2) (high z2))
	 (or (low r2) (high x1) (high y1))
	 (or (low r2) (high x1) (high r1))
	 (or (low r2) (high y1) (high r1))
	 (or (low x1) (low y1) (high r2))
	 (or (low x1) (low r1) (high r2))
	 (or (low y1) (low r1) (high r2))
	 (or (low z1) (low x1) (high y1) (low r1))
	 (or (low z1) (low x1) (low y1) (high r1))
	 (or (low z1) (high x1) (low y1) (low r1))
	 (or (low z1) (high x1) (high y1) (high r1))
	 (or (low x1) (low y1) (low r1) (high z1))
	 (or (low x1) (high y1) (high r1) (high z1))
	 (or (high x1) (low y1) (high r1) (high z1))
	 (or (high x1) (high y1) (low r1) (high z1))
	 )
  )
 )
